name: Publish Docker image

on: 
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  check_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq
      
      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/*_release
          key: ${{ runner.os }}/release

      - name: check geo versions
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
          LATEST_RELEASE=$(curl --silent "https://api.github.com/repos/cloudposse/geodesic/releases/latest" | jq -r .tag_name)
          ls -l ~/geo_latest_release
          cat ~/geo_latest_release
          echo $LATEST_RELEASE
          if [[ (("$LATEST_RELEASE" != "$(cat ~/geo_latest_release)")) ]]; then
            echo $LATEST_RELEASE > ~/geo_latest_release
            echo "updating release"
            ls -l ~/geo_latest_release
            cat ~/geo_latest_release
          fi
        id: geo_updated

      - name: add geo version to cache
        if: steps.geo_updated.outcome == 'failure'
        run: curl --silent "https://api.github.com/repos/cloudposse/geodesic/releases/latest" | jq -r .tag_name > ~/geo_latest_release

      # - name: check atmos versions
      #   if: steps.cache.outputs.cache-hit == 'true'
      #   run: |
      #     LATEST_RELEASE=$(curl --silent "https://api.github.com/repos/cloudposse/atmos/releases/latest" | jq -r .tag_name > ~/atmos_latest_release)
      #     if [[ "$LATEST_RELEASE" != "$(cat ~/atmos_latest_release)" ]]; then
      #       echo $LATEST_RELEASE > ~/atmos_latest_release
      #     fi
      #   id: atmos_updated

      - name: check for release updates
        if: steps.geo_updated.outcome == 'success'
        run: exit 0
        id: release_updated

      - name: No updates available
        if: steps.release_updated.outcome == 'failure'
        run: exit 1



      
          
  push_to_registry:
    name: Push Docker image to Docker Hub
    needs: check_release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: markballew/geodesic
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
